version: '3.8'
services:
  mongodb_test:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=test_db
    volumes:
      - mongodb_test_data:/data/db
volumes:
  mongodb_test_data:
